### ISSUE TITLE
Tabs opened from links don't appear in dropdown

### ISSUE THREAD

**Issue by garyking** [fwextensions/QuicKey#16] opened 2019-09-10 21:43 UTC
1. Open a link in a new tab by middle-clicking on it.
2. In QuicKey, search for the tab. The tab will appear in the results. But it doesn't appear in the dropdown at all, when it should possibly be the most recent item.

**Comment by fwextensions** [comment] 2019-09-12 06:15
Yeah, I've been thinking about this.  It's not in the recent list because you haven't actually activated the tab yet.  But there is a sense in which you visited it by clicking the link.

The extension doesn't currently listen for the `onCreated` event because in most cases, that's immediately followed by `onActivated`.  But when you control-click links, they don't get activated.

Relatedly, when a tab is closed, it should maybe switch back to the last active tab, not the tab to the left of it, which is what Chrome normally shows.

**Comment by garyking** [comment] 2019-10-06 21:04
Another scenario. 

I opened several tabs by middle-clicking a bookmark folder. I close the current tab, which focuses me on one of the tabs that was opened from the bookmark folder. I open a new tab. I want to go back to the last tab (the one opened from the bookmark folder), but it doesn't appear in the Quickey results, even though the tab was technically "activated", since I focused it at least once.

**Comment by fwextensions** [comment] 2019-10-07 02:36
That sounds like a bug, but I'm not able to reproduce it.  These are the steps I took:

* Open a new window
* Navigate to a page
* Open the Bookmarks page
* Right-click a folder and select *Open all bookmarks*
* Close the Bookmarks tab (which is still the current tab)

Doing that returns to the first tab I'd opened, not the ones that were opened from the Bookmarks page.  The recent tabs list doesn't include the tabs opened from the folder since none of them have been activated yet.  But I agree including those in some way probably makes sense.

**Comment by garyking** [comment] 2019-10-07 03:34
Not sure if it makes a difference, but I middle-clicked a bookmark folder in my "Bookmarks Bar" in Chrome, so I didn't have to open my bookmarks page in its own tab.

**Comment by fwextensions** [comment] 2019-11-11 02:58
The only way I'm able to reproduce your Oct 6 scenario is if I open the new tab within 750ms of closing the original tab.  That's the minimum time you need to pause on a tab for it to count as "active".  During that time, the QuicKey icon is inverted (black Q on grey), so if you switch to another tab while it's inverted (like by opening a new tab), the tab you had switched to after closing the original tab wouldn't count as getting activated, and therefore wouldn't be in the recents list.

Let me know if you're able to reproduce this after waiting long enough for the icon to switch back before opening the new tab.

**Comment by fwextensions** [comment] 2019-11-11 03:56
I have QuicKey now detecting tabs that were opened behind the current one and making them the "most recent", so that they appear in the recent list and you can toggle to them.  Let me know if this flow makes sense

1. Open tab 1 in a new session, recent list is empty
1. Open tab 2.  Recent list is `[1]`.
1. Middle-click a folder with 4 tabs in it.  Recent list is `[6, 5, 4, 3, 1]`.

So the current tab is 2, and the first item in the QuicKey menu is 6, since that was the last one to be opened from the folder.  If you pressed `alt-Z` now, you'd switch to tab 6, and 2 would become the first item in the list.  

Does that make sense?

**Comment by garyking** [comment] 2019-11-16 19:44
Yeah, that sounds good.

**Comment by fwextensions** [comment] 2019-12-18 00:51
This is now available in v1.3.0.

**Closed by fwextensions** 2019-12-18 00:51 UTC
Labels: enhancement
