### ISSUE TITLE
MRU list navigation using W doesn't work with non-Roman keyboard layouts on MAC

### ISSUE THREAD

**Issue by magicdarvin** [fwextensions/QuicKey#1] opened 2019-01-02 16:44 UTC
Hello, 

If I'm using a non-Roman keyboard layout (e.g. Cyrillic) on my mac I still can open the MRU list with ctrl+q shortcut but nothing happens when I press 'w' (while keep holding ctrl). 

Otherwise the extension is brilliant! 
Hope this bug could be fixed, thank you.

**Comment by fwextensions** [comment] 2019-01-02 21:56
Thanks for reporting the issue!  Glad you're finding the extension useful.  

I'm unfamiliar with how other keyboard layouts work on macOS and how they interact with browser key events.  I'm assuming this is a virtual layout, with a physical English keyboard?  Some other questions below:

* If you type w without ctrl, what character is shown in the search field?  I'm assuming the associated Cyrillic one. 
* If you press ctrl-Q to open the menu, release ctrl, and then press ctrl-W, does that work? 
* Does pressing cmd-ctrl-W to close a tab work? 
* Does pressing ctrl-A to switch to the previous tab work? 

I'm betting that the string being reported by in the JS keyboard event is the Cyrillic one, which is why the shortcut isn't working.  I'm also guessing that Chrome is using the letter on the physical key to trigger extension shortcuts, which is why ctrl-Q still works (though I wonder if it would still work with an English keyboard but a different layout, like Dvorak).  

I don't have a Mac at hand to test, so I'll see if I can replicate it on Windows.  If I create a beta version of the extension with possible fixes, would you be able to test it?

**Comment by magicdarvin** [comment] 2019-01-02 22:43
Thank you for such a quick reply.

Probably any keyboard layout is virtual in some sense. My macbook was produced for Russian market and it has a physical keyboard with both English and Russian characters engraved. 
![download](https://user-images.githubusercontent.com/1037742/50615540-aaf91780-0eed-11e9-83d8-dcf8bd09e754.jpeg)

The input is controlled by mac OS virtually using standard mac os features under System Preferences--> Keyboard --> Input Sources 
![screen shot 2019-01-03 at 12 25 06 am](https://user-images.githubusercontent.com/1037742/50615629-09be9100-0eee-11e9-8c86-d50726b9bd84.png)

- If I type 'w' without ctrl the associated Cyrillic character 'ц' appears in the search field;
- If I press ctrl-Q to open the menu, release ctrl, and then press ctrl-W that doesn't work;
- cmd-ctrl-W doesn't work if the input source is Russian;
- ctrl-A does work and switches to the previous tab successfully! 

I've tried DVORAK. It drastically changes how all shortcuts operate on the computer. Both ctrl-q and ctrl-w work but they are mapped to totally different physical keys. w is in place of x and w is in place of ','. If I'm using the Polish layout for example both ctrl+q and ctrl+w work fine, but the Polish keyboard has w mapped to the same physical key as in the English keyboard. If I'm using another non-Roman layout such as Ukrainian (also a Cyrillic alphabet) the behavior is the same as with the Russian layout. 

Sure, I'll be able to test a beta version! 
Thanks!

**Comment by fwextensions** [comment] 2019-01-03 00:05
Thanks for all the additional info.  I'm able to repro it Win10 with other virtual keyboards.  

In modern browsers, it is possible to distinguish the physical key from what is typed in the keyboard events.  So pressing the <kbd>ц</kbd> key sends `"KeyW"` as the `code` value and `"ц"` as the `key`.

The problem is, even in Romance languages that contain A-Z, but in a different layout, or alternate layouts like Dvorak, the standard QWERTY codes are still sent.  From what I've read, this is true even for physical keyboards.  So a physical French AZERTY keyboard would send `"KeyQ"` as the `code` if the user pressed <kbd>A</kbd>, which seems a little nutty, given that there's still a physical <kbd>Q</kbd> key.

The challenge is I'm not sure yet if there's a way to distinguish these cases.  For the Cyrillic case, it makes sense to use the `code` value, since the physical keys have those letters on them, too.  But for the French case, the user would expect to press the physical <kbd>W</kbd> key, which would send `"KeyZ"`, which then wouldn't work.  In that case, it would be better to look at the `key` value instead of `code`.

Interestingly, the Chrome extensions keyboard shortcuts page seems to do the right thing.  When a Cyrillic layout is selected, pressing the physical <kbd>C</kbd> key shows up as <kbd>C</kbd> in the shortcut.  But with a Dvorak layout, pressing <kbd>C</kbd> shows up as <kbd>J</kbd>, which is what a Dvorak user would expect.  I'm going to dig into the code in that page to try to figure out how they're doing it.  It may be a special API not accessible to extensions.

**Comment by fwextensions** [comment] 2019-01-05 23:06
I think I have a fix for this.  Do you know how to load an unpacked extension?

**Comment by magicdarvin** [comment] 2019-01-05 23:19
Wow! Great! I think I did load unpacked extension ones before and there are plenty of guidelines online, so I think I can handle it

**Comment by fwextensions** [comment] 2019-01-06 00:15
Okay, download this and unzip it somewhere: https://github.com/fwextensions/QuicKey/archive/feature/intl-keyboards.zip

Go to the Extensions page, make sure *Developer mode* is on, then click *Load unpacked*.  Select the `src/` folder inside the unzipped archive, not the top-level folder.  Then another copy of QuicKey should appear in the extensions list.  The local one will have a red icon on it.  

You'll probably want to give it another keyboard shortcut, like <kbd>ctrl</kbd><kbd>E</kbd>.  Then pressing <kbd>W</kbd> with <kbd>ctrl</kbd> down should navigate the list, and the other shortcuts should work, too.

Let me know if it works for you.

**Comment by fwextensions** [comment] 2019-01-06 02:31
I just pushed another version that fixes the <kbd>ctrl</kbd><kbd>[</kbd> shortcut, which the previous change had broken.

**Comment by magicdarvin** [comment] 2019-01-06 09:42
The extension seems to be working well both in English and Russian layouts!

**Comment by fwextensions** [comment] 2019-01-07 01:10
Thanks for the confirmation!  I've pushed [v1.0.2](https://github.com/fwextensions/QuicKey/releases/tag/v1.0.2) with the fix to the Chrome store.  

Adding a review here wouldn't hurt.  ;)  https://chrome.google.com/webstore/detail/quickey-%E2%80%93-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg

I think I'll add the ability to customize the navigation shortcuts, now that I know at least one user has a non-QWERTY keyboard.

**Closed by fwextensions** 2019-01-07 01:10 UTC
