### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by chad-abizeid** [fwextensions/QuicKey#102] opened 2023-04-30 11:39 UTC
Trying option #1 here: https://fwextensions.github.io/QuicKey/ctrl-tab/#option-1

Getting an error on pasting the code (key matches key in address bar too).

```
chrome.developerPrivate.updateExtensionCommand({
    extensionId: "mcjciddpjefdpndgllejgcekmajmehnd",
    commandName: "30-toggle-recent-tabs",
    keybinding: "Ctrl+Tab"
});
```

VM22:1 Uncaught TypeError: Cannot read properties of undefined (reading 'updateExtensionCommand')
    at <anonymous>:1:25
(anonymous) @ VM22:1

**Comment by fwextensions** [comment] 2023-05-06 23:36
Duplicate of #103

**Closed by fwextensions** 2023-05-06 23:36 UTC
